// <auto-generated />
using System;
using ImmatureBackend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImmatureBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917112725_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImmatureBackend.Domain.Models.ReplicateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiPredictedGrains")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_predicted_grains");

                    b.Property<string>("ConfirmedGrains")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confirmed_grains");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<decimal>("ImmatureWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("immature_weight");

                    b.Property<byte[]>("OriginalImage")
                        .HasColumnType("bytea")
                        .HasColumnName("original_image");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_status");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sample_id");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("technician_name");

                    b.HasKey("Id");

                    b.ToTable("replicates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
